<?php

namespace BlogBundle\Repository;

/**
 * ArtisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtisteRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($recherche){
        $q = $this->createQueryBuilder('p')
            ->where('p.nom LIKE :recherche')
            ->setParameter('recherche', '%'.$recherche.'%')
            ->orderBy('p.id', 'ASC')
            ->getQuery();
            return $q;
    }
}
