<?php

namespace BlogBundle\Repository;

/**
 * ChansonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChansonsRepository extends \Doctrine\ORM\EntityRepository
{
}
